### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by morizotter** [davbeck/TUSafariActivity#22] opened 2015-09-22 06:44 UTC
It's better to have carthage support.

**Comment by minacle** [comment] 2018-06-01 02:55
@davbeck close this issue because of TUSafariActivity is already carthage compatible since e98aa4f.

**Comment by eduardbosch** [comment] 2019-04-10 13:08
I'm using this lib with Carthage and it doesn't work if I specify the dependencylike this:

`github "davbeck/TUSafariActivity" ~> 1.0.0`

I have to specify the dependency from the master branch like this:
`github "davbeck/TUSafariActivity" "master"`

The problem is that when I use the definition with version, carthage downloads the [souce code zip](https://github.com/davbeck/TUSafariActivity/archive/1.0.4.zip) file that does not contains the xcode project.
Removing the source code zip file from github releases will solve this issue.

**Comment by davbeck** [comment] 2023-10-21 23:30
Should work now with https://github.com/davbeck/TUSafariActivity/releases/tag/1.0.5.

**Closed by davbeck** 2023-10-21 23:30 UTC
